import 'dart:convert';

import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  late Map<String, String> _localizedStrings;

  Future<bool> load() async {
    final raw = _allValues[locale.languageCode] ?? _allValues['en']!;
    _localizedStrings = raw.map(
      (key, value) => MapEntry(key, _normalizeText(value)),
    );
    return true;
  }

  String translate(String key) {
    return _localizedStrings[key] ??
        _normalizeText(_allValues['en']?[key] ?? key);
  }

  String _normalizeText(String value) {
    if (value.isEmpty) {
      return value;
    }

    var current = value;
    for (var i = 0; i < 10; i++) {
      if (!_looksMojibake(current)) {
        break;
      }
      final repaired = _repairMojibakeOnce(current);
      if (repaired == current) {
        break;
      }
      current = repaired;
    }
    return current;
  }

  bool _looksMojibake(String value) {
    const suspiciousFragments = [
      'Ã',
      'Â',
      'â',
      'ï',
      '�',
      '\u0081',
      '\u008d',
      '\u008f',
      '\u0090',
      '\u009d',
    ];

    return suspiciousFragments.any(value.contains);
  }

  String _repairMojibakeOnce(String value) {
    try {
      return utf8.decode(latin1.encode(value), allowMalformed: true);
    } catch (_) {
      return value;
    }
  }

  static final Map<String, Map<String, String>> _allValues = {
    'en': {
      'app_title': 'Sahla',
      'search_hint': 'Search products...',
      'categories': 'Categories',
      'featured_products': 'Featured Products',
      'add_to_cart': 'Add to Cart',
      'buy_now': 'Buy Now',
      'profile': 'My Profile',
      'orders': 'My Orders',
      'wishlist': 'My Wishlist',
      'settings': 'Settings',
      'language': 'Language',
      'dark_mode': 'Dark Mode',
      'logout': 'Logout',
      'message_store': 'Message Store',
      'follow': 'Follow',
      'following': 'Following',
      'followers': 'Followers',
      'products': 'Products',
      'store_description': 'Browse products from this seller.',
      'search_in_store': 'Search in this store...',
      'cart': 'Cart',
      'checkout': 'Checkout',
      'total': 'Total',
      'recently_viewed': 'Recently Viewed',
      'similar_products': 'Similar Products',
      'shopping_activity': 'Shopping Activity',
      'account_settings': 'Account Settings',
      'support_info': 'Support & Info',
      'shipping_address': 'Shipping Address',
      'payment_methods': 'Payment Methods',
      'help_center': 'Help Center',
      'about_sahla': 'About Sahla',
      'about_us_title': 'About Us',
      'about_app_name': 'Marketplace App',
      'about_app_version': 'Version 1.0.0',
      'about_mission_title': 'Our Mission',
      'about_mission_body':
          'We aim to provide a seamless and enjoyable e-commerce experience across Algeria by connecting trusted sellers with buyers.',
      'about_why_title': 'Why Choose Us?',
      'about_feature_auth_title': 'Genuine Products',
      'about_feature_auth_desc':
          'We work to ensure product authenticity and trusted seller standards.',
      'about_feature_delivery_title': 'Fast Delivery',
      'about_feature_delivery_desc':
          'Our logistics partners help deliver orders quickly and reliably.',
      'about_feature_support_title': '24/7 Support',
      'about_feature_support_desc':
          'Our team is available to help with order and account issues anytime.',
      'profile_hub_subtitle':
          'A cleaner account hub with grouped shortcuts and settings.',
      'quick_access_title': 'Quick Access',
      'quick_access_subtitle':
          'Core account widgets are grouped here for faster navigation.',
      'order_insights_title': 'Order Insights',
      'order_insights_subtitle':
          'Live order states are separated into clearer summary widgets.',
      'account_tools_title': 'Account Tools',
      'account_tools_subtitle':
          'Personal details, payment setup, and app preferences are separated into one place.',
      'support_info_title': 'Support and Info',
      'support_info_subtitle':
          'Help resources and product information are split out from account settings.',
      'guest_workspace': 'Guest Workspace',
      'browse_mode': 'Browse Mode',
      'admin_access': 'Admin Access',
      'seller_account': 'Seller Account',
      'buyer_account': 'Buyer Account',
      'email_verified_status': 'Email Verified',
      'verify_email_status': 'Verify Email',
      'profile_sign_in_hint':
          'Sign in to sync addresses, orders, and saved products.',
      'profile_store_ready':
          'Store is ready for publishing and order management.',
      'profile_store_setup_progress': 'Seller setup is still in progress.',
      'profile_ready_checkout':
          'Profile is ready for checkout and delivery updates.',
      'profile_add_phone':
          'Add a phone number to speed up checkout and support.',
      'logout_device_hint': 'Sign out from this device when you are done.',
      'awaiting_completion': 'Awaiting completion',
      'packages_in_transit': 'Packages in transit',
      'orders_stopped': 'Orders stopped',
      'review_ready_items': 'Review ready items',
      'about_story_subtitle':
          'The same visual language as the profile hub, but focused on brand and trust.',
      'about_core_reasons_subtitle':
          'Core reasons customers and sellers use Sahla.',
      'support_shell_subtitle':
          'Fast access to support contacts and the in-app ticket form.',
      'settings_shell_subtitle':
          'Language, region, AI, cache, and account preferences in one place.',
      'password_reset_email_sent':
          'Password reset email sent. Please check your inbox.',
      'notifications_center_subtitle':
          'Track updates, promotions, and order changes from one place.',
      'discover_products': 'Discover Products',
      'search_discover_subtitle':
          'Search across categories, brands, and recent trends on Sahla.',
      'home_hub_subtitle':
          'Fresh picks, categories, and deals shaped with the same profile-inspired design.',
      'track_delivery_states': 'Track delivery states',
      'saved_products': 'Saved products',
      'resume_browsing': 'Resume browsing',
      'moderation_tools': 'Moderation tools',
      'store_performance': 'Store performance',
      'update_profile_details': 'Update your details and profile image.',
      'refresh_contact_info':
          'Refresh your contact info, avatar, and seller fields.',
      'keep_delivery_locations_organized': 'Keep delivery locations organized.',
      'manage_checkout_methods': 'Manage your preferred checkout methods.',
      'settings_summary': 'Language, region, AI, cache, and notifications.',
      'contact_support_resolve': 'Contact support and resolve account issues.',
      'read_more_marketplace': 'Read more about the marketplace and app.',
      'logout_confirm': 'Are you sure you want to sign out?',
      'cancel': 'Cancel',
      'seller_dashboard': 'Seller Dashboard',
      'to_pay': 'To Pay',
      'to_ship': 'To Ship',
      'to_receive': 'To Receive',
      'to_review': 'To Review',
      'sahla_member': 'Sahla Member',
      'welcome_guest': 'Welcome Guest',
      'sign_in_sync': 'Sign in to sync your data',
      'explore': 'Explore',
      'home': 'Home',
      'my_store': 'My Store',
      'help_support': 'Help & Support',
      'categories_subtitle': 'Browse the most active departments.',
      'categories_page_subtitle':
          'Move through departments horizontally, then sort and filter the catalog faster.',
      'flash_deals': 'Flash Deals',
      'flash_deals_subtitle': 'Limited-time price drops worth catching.',
      'featured_products_subtitle': 'Curated picks across the marketplace.',
      'welcome_sahla_market': 'Welcome to Sahla Marketplace',
      'sahla_user': 'Sahla User',
      'season_sale': 'Season Sale',
      'up_to_70_off': 'Up to 70% OFF',
      'new_gadgets': 'New Gadgets',
      'smart_tech_2024': 'Smart Tech 2024',
      'phones': 'Phones',
      'laptops': 'Laptops',
      'fashion': 'Fashion',
      'home_category': 'Home',
      'seller_store': 'Seller Store',
      'discover_seller_products': 'Discover products from this seller.',
      'in_stock': 'in stock',
      'out_of_stock': 'Out of stock',
      'reviews': 'reviews',
      'overview': 'Overview',
      'specs': 'Specs',
      'poster_details': 'Poster Details',
      'poster_details_subtitle':
          'More visual details shared by the seller for this product.',
      'image_load_error': 'This detail image could not be loaded.',
      'customer_reviews': 'Customer Reviews',
      'no_reviews_yet': 'No reviews yet.',
      'based_on': 'Based on',
      'customer_review_count': 'customer review',
      'customer_review_count_plural': 'customer reviews',
      'write_review': 'Write Review',
      'verified_purchase': 'Verified Purchase',
      'first_review_prompt':
          'No reviews yet. Be the first customer to leave feedback after purchase.',
      'added_to_cart': 'added to cart',
      'available_options': 'Available Options',
      'colors': 'Colors',
      'sizes': 'Sizes',
      'share': 'Share',
      'no_written_comment': 'No written comment.',
      'my_cart': 'My Cart',
      'cart_empty_title': 'Your Cart Is Empty',
      'cart_empty_subtitle': 'Looks like you have not added anything yet.',
      'start_shopping': 'Start Shopping',
      'review_items': 'Review your items',
      'items_ready_checkout': 'items ready for checkout.',
      'subtotal': 'Subtotal',
      'shipping': 'Shipping',
      'payment': 'Payment',
      'review': 'Review',
      'place_order': 'Place Order',
      'pay_now': 'Pay Now',
      'continue_btn': 'Continue',
      'back': 'Back',
      'shipping_details': 'Shipping Details',
      'shipping_desc': 'Tell us where the order should go.',
      'wilaya_commune': 'Wilaya & Commune',
      'commune': 'Commune',
      'commune_hint': 'Enter your commune',
      'detailed_address': 'Detailed Address',
      'address_hint': 'House number, street name, building...',
      'delivery_type': 'Delivery Type',
      'select_carrier': 'Select Carrier',
      'coming_soon': 'Coming Soon',
      'home_delivery': 'Home Delivery',
      'stop_desk': 'Stop-Desk (Yalidine/ZR)',
      'select_agency': 'Select Pickup Point',
      'choose_pickup_point': 'Choose a stop-desk office',
      'no_pickup_points_for_wilaya':
          'No stop-desk pickup points are available for this wilaya.',
      'select_pickup_point_error':
          'Select a pickup point before continuing with stop-desk delivery.',
      'stop_desk_checkout_hint':
          'For stop-desk delivery, choose the pickup office where the customer will collect the parcel.',
      'delivery_status': 'Delivery Status',
      'sync_tracking': 'Sync Tracking',
      'tracking_synced': 'Tracking synced successfully.',
      'tracking_sync_failed': 'Could not sync tracking: {error}',
      'standard_home_delivery': 'Standard Home Delivery',
      'collect_from_office': 'Collect from Office',
      'est_arrival_days': 'Est. Arrival: 2-4 days',
      'available_days': 'Available in 1-2 days',
      'select_payment_method': 'Select Payment Method',
      'payment_method_desc': 'Choose how you want to complete the order.',
      'cod': 'Cash on Delivery (COD)',
      'cod_desc': 'Pay when you receive your order',
      'chargily_online': 'Chargily (CIB / Edahabia)',
      'chargily_online_desc': 'Pay online and confirm instantly after payment.',
      'edahabia': 'Edahabia (AlgÃƒÆ’Ã‚Â©rie Poste)',
      'edahabia_desc': 'Fast and secure local payment',
      'cib_card': 'CIB Card',
      'cib_card_desc': 'Interbank card payment',
      'order_summary': 'Order Summary',
      'review_pricing_desc': 'Review pricing before placing the order.',
      'shipping_fee': 'Shipping Fee',
      'total_amount': 'Total Amount',
      'dzd': 'DZD',
      'final_confirmation': 'Final Confirmation',
      'terms_privacy_agreement':
          'By clicking "Place Order", you agree to Sahla\'s Terms of Service and Privacy Policy.',
      'payment_success': 'Payment Success!',
      'order_confirmed': 'Order Confirmed',
      'order_placed_msg':
          'Your order has been placed successfully.\nWe\'ll notify you when it ships!',
      'order_placed_payment_open':
          'Order placed. Continue payment from the opened Chargily page.',
      'order_payment_open_failed':
          'Order placed, but payment page did not open: {error}',
      'checkout_cod_only':
          'Cash on delivery is currently the only supported payment method.',
      'checkout_online_payments_disabled':
          'Online card storage and gateway checkout stay disabled until a verified payment integration is live.',
      'return_to_home': 'Return to Home',
      'cart_empty': 'Your cart is empty',
      'notifications': 'Notifications',
      'sign_in_required': 'Sign in required',
      'sign_in_notifications_msg':
          'Log in to see updates about orders, promotions, and delivery activity.',
      'notifications_unavailable': 'Notifications unavailable',
      'notifications_load_error':
          'We could not load your notifications right now. Please try again in a moment.',
      'go_back': 'Go Back',
      'mark_all_read': 'Mark all read',
      'no_notifications': 'No notifications yet',
      'no_notifications_msg':
          'We will notify you when something important happens with your orders, deals, or store activity.',
      'mins_ago': 'mins ago',
      'hours_ago': 'hours ago',
      'days_ago': 'days ago',
      'my_wishlist': 'My Wishlist',
      'wishlist_empty_plain': 'Your wishlist is empty',
      'wishlist_empty_plain_subtitle':
          'Save items you love to find them later.',
      'saved_picks': 'Saved picks',
      'wishlist_items_ready': '{count} items ready when you are.',
      'wishlist_empty_title': 'Your Wishlist is Empty',
      'wishlist_empty_subtitle': 'Save items you like to see them here.',
      'search_sahla': 'Search Sahla...',
      'recent_searches': 'Recent Searches',
      'clear': 'Clear',
      'popular_categories': 'Popular Categories',
      'popular_categories_subtitle':
          'Jump back into the sections people browse most.',
      'browse_category_picks': 'Browse {category} picks',
      'no_products_found': 'No products found',
      'search_products_prompt': 'Search for products...',
      'start_searching_msg': 'Start searching for products',
      'filter_results': 'Filter Results',
      'filter_desc': 'Refine your search by price and rating.',
      'sort_label': 'Sort',
      'sort_relevance': 'Recommended',
      'sort_newest': 'Newest',
      'sort_price_low_high': 'Price: Low to High',
      'sort_price_high_low': 'Price: High to Low',
      'sort_rating_high': 'Highest Rating',
      'sort_popular': 'Most Popular',
      'rating_any': 'Any rating',
      'rating_3_plus': '3.0+ stars',
      'rating_4_plus': '4.0+ stars',
      'in_stock_only': 'In stock only',
      'price_range': 'Price Range',
      'apply_filters': 'Apply Filters',
      'my_orders': 'My Orders',
      'all': 'All',
      'orders_unavailable': 'Orders unavailable',
      'orders_load_error':
          'We could not load your orders right now. Please try again later.',
      'no_orders_yet': 'No Orders Yet',
      'no_status_orders': 'No {status} Orders',
      'order_history_desc': 'Your purchase history will appear here.',
      'shop_now': 'Shop Now',
      'order_id': 'ID',
      'items_count': '{count} Items',
      'cancel_order': 'Cancel Order',
      'mark_received': 'Mark Received',
      'write_review_btn': 'Write Review',
      'confirm_delivery': 'Confirm delivery',
      'confirm_delivery_msg':
          'Mark this order as received and ready for review?',
      'order_received_msg': 'Order marked as received.',
      'cancel_order_title': 'Cancel order',
      'cancel_order_msg': 'Do you want to cancel this order before it ships?',
      'order_cancelled_msg': 'Order cancelled.',
      'yes': 'Yes',
      'no': 'No',
      'awaiting_confirmation': 'Awaiting seller confirmation',
      'on_its_way': 'On its way to you',
      'package_delivered': 'Package delivered',
      'seller_preparing': 'Seller is preparing your order',
      'you_confirmed_delivery': 'You confirmed the delivery',
      'order_is_cancelled': 'This order has been cancelled',
      'est_delivery_days': 'Estimated delivery in 2-4 days',
      'messages': 'Messages',
      'inbox': 'Inbox',
      'inbox_subtitle': 'Your latest conversations and seller chats.',
      'start_conversation': 'Start a Conversation',
      'start_conversation_subtitle': 'Search for users by name or store name.',
      'search_users_hint': 'Search for users...',
      'no_users_found': 'No users found.',
      'search_unavailable': 'Search unavailable',
      'type_to_search': 'Type to start searching',
      'messages_unavailable': 'Messages unavailable',
      'messages_load_error':
          'We could not load your conversations right now. Please try again later.',
      'no_conversations_yet': 'No conversations yet',
      'no_conversations_msg': 'Start a conversation to see it here.',
      'delete_chat': 'Delete conversation',
      'delete_chat_confirm': 'Delete this conversation for both participants?',
      'delete': 'Delete',
      'recipient_error': 'Could not load recipient details.',
      'no_messages_yet': 'No messages yet',
      'image_send_error': 'Could not send your image.',
      'message_send_error': 'Could not send your message right now.',
      'conversation_unavailable': 'Conversation unavailable',
      'conversation_load_error':
          'We could not load this chat right now. Please try again later.',
      'say_hello_to': 'Say hello to {name} to start the conversation.',
      'write_message_hint': 'Write a message...',
      'edit_store_info': 'Edit Store Info',
      'store_name': 'Store Name',
      'store_description_label': 'Store Description',
      'save': 'Save',
      'store_name_empty': 'Store name cannot be empty.',
      'store_not_found': 'Store not found',
      'store_not_found_msg': 'We could not determine which store to show here.',
      'add_product': 'Add Product',
      'store_unavailable': 'Store unavailable',
      'store_load_error': 'We could not load this store right now.',
      'manage_storefront': 'Manage your storefront and orders.',
      'browse_seller_products': 'Browse products from this seller.',
      'message': 'Message',
      'pending': 'Pending',
      'processing': 'Processing',
      'shipped': 'Shipped',
      'delivered': 'Delivered',
      'received': 'Received',
      'cancelled': 'Cancelled',
      'completed': 'Completed',
      'verified_seller': 'Verified Seller',
      'weekly_views': 'Weekly Views',
      'weekly_clicks': 'Weekly Clicks',
      'weekly_sales': 'Weekly Sales',
      'top_product': 'Top Product',
      'my_products': 'My Products',
      'store_products': 'Store Products',
      'my_products_subtitle': 'Everything currently listed in your store.',
      'store_products_subtitle':
          'Products currently available from this seller.',
      'seller_approval_pending': 'Seller approval pending',
      'seller_approval_pending_msg':
          'Your store can be edited, but product publishing stays locked until an admin approves the seller account and a phone number is added.',
      'no_products_yet': 'No products yet',
      'no_products_yet_msg':
          'Products will appear here once this store starts listing them.',
      'no_results_found': 'No results found',
      'search_no_results_msg': 'Try searching with different keywords.',
      'edit_product': 'Edit Product',
      'request_refund': 'Request Refund',
      'refund_reason_hint': 'Wrong item, damaged, order cancelled...',
      'refund_details_hint': 'Add order details for the admin team.',
      'refund_request_submitted': 'Refund request submitted.',
      'report_product': 'Report Product',
      'report_reason': 'Reason',
      'report_reason_hint': 'Fake item, scam, prohibited product...',
      'report_details': 'Details',
      'report_details_hint': 'Add anything that helps the admin review it.',
      'product_report_submitted': 'Product report submitted.',
      'unable_share_product': 'Unable to share product right now.',
      'product_share_template':
          '{name}\n{description}\n\nPrice: {price} {currency}\nCategory: {category}\nShared from Sahla.',
      'sign_in_report_products': 'Sign in to report products.',
      'refine_listing': 'Refine your listing',
      'create_strong_listing': 'Create a stronger listing',
      'listing_subtitle':
          'Add a gallery, poster-style detail images, options, and a cleaner description.',
      'product_gallery': 'Product Gallery',
      'gallery_subtitle':
          'These appear at the top of the product page. The first image becomes the cover.',
      'poster_detail_images': 'Poster Detail Images',
      'poster_subtitle':
          'These appear below the description like a long product story.',
      'add_images': 'Add Images',
      'add_more_images': 'Add More Images',
      'product_name': 'Product Name',
      'product_name_hint': 'e.g. Support Brace Pro',
      'price_dzd': 'Price (DZD)',
      'stock': 'Stock',
      'main_description': 'Main Description',
      'description_hint':
          'Write the core product pitch. Detail images below will turn this into a richer poster-style page.',
      'available_colors_label': 'Available Colors',
      'colors_subtitle': 'Add simple names like Black, White, Blue.',
      'add_color': 'Add a color',
      'available_sizes_label': 'Available Sizes',
      'sizes_subtitle': 'Examples: S, M, L, XL, 42, 43.',
      'add_size': 'Add a size',
      'save_changes': 'Save Changes',
      'confirm': 'Confirm',
      'submit': 'Submit',
      'finish_setup': 'Finish Setup',
      'publish_product': 'Publish Product',
      'add_at_least_one_image': 'Please add at least one product image.',
      'product_updated': 'Product updated successfully.',
      'product_published': 'Product published successfully.',
      'field_required': 'This field is required',
      'valid_non_negative_price': 'Enter a valid non-negative price',
      'valid_non_negative_stock': 'Enter a valid non-negative stock quantity',
      'auth_session_expired': 'User not logged in or session expired',
      'seller_only_publish': 'Only seller accounts can publish products',
      'seller_publish_blocked':
          'Your seller account is not ready to publish products yet.',
      'category': 'Category',
      'subcategory_count': '{category} • {count} subcategories',
      'selected_category': 'Selected: {category}',
      'main_category': 'Main Category',
      'sub_category': 'Subcategory',
      'brand': 'Brand',
      'brand_hint': 'e.g. Apple, Samsung, Zara',
      'top_category': 'Top Category',
      'trust_badge': 'Trust',
      'view_store': 'View Store',
      'add': 'Add',
      'unable_save_product': 'Unable to save this product: {error}',
      'store_orders': 'Store Orders',
      'login_seller_orders_msg':
          'Log in with your seller account to manage store orders.',
      'no_orders_found': 'No orders found',
      'no_status_orders_store': 'No {status} orders',
      'store_orders_empty_msg':
          'Orders containing your products will appear here as customers place them.',
      'try_different_filter_msg':
          'Try a different filter to view more store orders.',
      'order_id_prefix': 'Order #',
      'qty_prefix': 'Qty: ',
      'buyer_id_prefix': 'Buyer ID: ',
      'buyer_name': 'Buyer',
      'buyer_phone': 'Buyer Phone',
      'seller_subtotal': 'Seller Subtotal',
      'mark_as_shipped': 'Mark as Shipped',
      'mark_as_delivered': 'Mark as Delivered',
      'mark_order_delivered_title': 'Mark this order as delivered?',
      'mark_order_delivered_msg':
          'This will notify the buyer that the order was delivered.',
      'status_pending_approval': 'PENDING APPROVAL',
      'status_approved': 'APPROVED',
      'status_verified': 'VERIFIED',
      'status_cod_blocked': 'COD BLOCKED',
      'status_suspended': 'SUSPENDED',
      'status_open': 'Open',
      'status_in_progress': 'In Progress',
      'status_reviewing': 'Reviewing',
      'status_resolved': 'Resolved',
      'status_closed': 'Closed',
      'status_dismissed': 'Dismissed',
      'status_rejected': 'Rejected',
      'status_refunded': 'Refunded',
      'reporter_label': 'Reporter',
      'seller_label': 'Seller',
      'updating_btn': 'Updating...',
      'cancel_this_order': 'Cancel this order?',
      'cancel_order_notify_msg':
          'This will notify the buyer that the order has been cancelled.',
      'pending_filter': 'Pending',
      'processing_filter': 'Processing',
      'shipped_filter': 'Shipped',
      'delivered_filter': 'Delivered',
      'cancelled_filter': 'Cancelled',
      'total_earnings': 'Total Earnings',
      'no_orders_sign_in': 'Sign in required to manage orders.',
      'sign_in_seller_desc':
          'Log in with your seller account to manage store orders.',
      'electronics': 'Electronics',
      'computing': 'Computing',
      'tablets': 'Tablets',
      'data_storage': 'Data Storage',
      'gaming': 'Gaming',
      'men_fashion': 'Men Fashion',
      'women_fashion': 'Women Fashion',
      'kids_fashion': 'Kids Fashion',
      'baby_fashion': 'Baby Fashion',
      'home_decor': 'Home Decor',
      'sports': 'Sports',
      'watches': 'Watches',
      'shoes': 'Shoes',
      'accessories': 'Accessories',
      'bags': 'Bags',
      'kids': 'Kids',
      'off': 'OFF',
      'all_products': 'All Products',
      'see_all': 'See All',
      'error': 'Error',
      'generic_error_retry': 'Something went wrong. Please try again.',
      'authentication_failed': 'Authentication failed. Please try again.',
      'verify_email_before_sign_in':
          'Please verify your email before signing in.',
      'invalid_login_credentials': 'Incorrect email or password.',
      'google_sign_in_failed': 'Google sign-in is unavailable right now.',
      'store_orders_load_error':
          'We could not load store orders right now. Please try again later.',
      'update_order_failed': 'Unable to update this order right now.',
      'store_products_load_error':
          "We could not load this store's products right now.",
      'seller_analytics_load_error':
          'We could not load your seller analytics right now.',
      'update_follow_failed': 'Unable to update follow status.',
      'update_store_details_failed':
          'Unable to update store details right now.',
      'upload_store_image_failed_generic':
          'Unable to upload this image right now.',
      'invalid_server_response': 'The server returned an invalid response.',
      'review_submit_failed': 'Could not submit your review right now.',
      'profile_update_failed_generic':
          'Could not update your profile right now.',
      'no_items': 'No items',
      'try_another_category': 'Try another category',
      'search_on_sahla': 'Search on Sahla',
      'checkout_flow_subtitle':
          'Confirm shipping, payment, and review details in one guided flow.',
      'vendor_orders_subtitle':
          'Track fulfillment, buyer details, and shipping progress from one place.',
      'chargily': 'Chargily',
      'add_items_to_start_checkout':
          'Add products to your cart before starting checkout.',
      'invalid_checkout_response': 'Invalid checkout response from server.',
      'missing_checkout_url': 'Missing checkout URL from payment gateway.',
      'invalid_checkout_url': 'Invalid checkout URL.',
      'open_payment_page_failed': 'Could not open payment page.',
      'profile_settings': 'Profile Settings',
      'sign_in_edit_profile': 'Sign in is required to edit your profile.',
      'profile_updated_success': 'Profile updated successfully!',
      'store_setup': 'Store Setup',
      'sign_in_store_setup': 'Sign in is required to complete store setup.',
      'store_setup_success': 'Store setup completed successfully!',
      'store_setup_intro':
          'Welcome to Sahla! Let\'s set up your store identity so customers can recognize you.',
      'upload_logo_failed': 'Failed to upload logo: {error}',
      'payment_methods_cleanup_success': 'Legacy payment methods deleted.',
      'payment_methods_cleanup_error':
          'Unable to delete legacy payment methods: {error}',
      'online_payments_disabled_title': 'Online card payments are disabled',
      'online_payments_disabled_body':
          'Sahla does not store live card details in the app. Cash on delivery is the only active checkout method until a verified payment gateway is integrated.',
      'no_legacy_payment_methods':
          'No legacy payment methods are stored on your account.',
      'legacy_payment_methods_found':
          '{count} legacy payment method(s) were found from earlier app versions.',
      'deleting': 'Deleting...',
      'delete_legacy_payment_methods': 'Delete legacy payment methods',
      'cache_cleared_success': 'Cache cleared successfully.',
      'admin_panel': 'Admin Panel',
      'access_denied': 'Access denied',
      'admin_only_page': 'Only admin accounts can use this page.',
      'users': 'Users',
      'tickets': 'Tickets',
      'reports': 'Reports',
      'refunds': 'Refunds',
      'phone_label': 'Phone',
      'shipment_tracking': 'Shipment Tracking',
      'tracking_number': 'Tracking Number',
      'carrier_label': 'Carrier',
      'shipment_updates_unavailable': 'Shipment updates are not available yet.',
      'shipment_pending': 'Shipment has not been created yet.',
      'tracking_pending': 'Created in Elogistia, tracking pending.',
      'view_tracking': 'View Tracking',
      'retry_shipment_creation': 'Create Shipment',
      'creating_shipment': 'Creating shipment...',
      'shipment_created': 'Shipment created successfully.',
      'shipment_creation_failed': 'Shipment creation failed: {error}',
      'shipment_failed': 'Delivery attempt failed',
      'elogistia_shipment_warning':
          'Order placed, but shipment creation in Elogistia needs attention: {error}',
      'phone_missing': 'Phone: missing',
      'ban_reason': 'Ban reason',
      'revoke_approval': 'Revoke approval',
      'approve_seller': 'Approve seller',
      'unblock_cod': 'Unblock COD',
      'block_cod': 'Block COD',
      'unsuspend': 'Unsuspend',
      'suspend': 'Suspend',
      'admin_note': 'Admin note',
      'deleted_product': 'Deleted product',
      'reason': 'Reason',
      'delete_product': 'Delete product',
      'order_number_short': 'Order #',
      'order_total': 'Order total',
      'pending_sellers': 'Pending sellers',
      'sellers': 'Sellers',
      'buyers': 'Buyers',
      'suspended': 'Suspended',
      'search_admin_users_hint': 'Search by name, email, store, phone',
      'try_another_filter': 'Try another filter or search term.',
      'suspend_user': 'Suspend user',
      'suspend_reason_hint': 'Reason shown to support and audit logs',
      'update_ticket': 'Update ticket',
      'ticket_note_hint': 'Optional internal or user-facing note',
      'no_support_tickets': 'No support tickets',
      'support_tickets_will_appear': 'User support tickets will appear here.',
      'update_report': 'Update report',
      'moderation_note_hint': 'Optional moderation note',
      'no_product_reports': 'No product reports',
      'product_reports_will_appear': 'Reported products will appear here.',
      'update_refund_request': 'Update refund request',
      'refund_note_hint': 'Optional note for the buyer',
      'no_refund_requests': 'No refund requests',
      'refund_requests_will_appear': 'Refund requests will appear here.',
      'open_cases': 'Open Cases',
      'approved_sellers': 'Approved Sellers',
      'cancelled_orders': 'Cancelled Orders',
      'delivered_orders': 'Delivered Orders',
      'cod_blocked': 'COD Blocked',
      'risk_signals': 'Risk Signals',
      'risk_signals_subtitle':
          'Quick moderation hotspots from live marketplace activity.',
      'buyers_most_cancelled_orders': 'Buyers With Most Cancelled Orders',
      'no_buyer_cancellation_spikes': 'No cancelled-order spikes detected.',
      'sellers_most_cancelled_orders': 'Sellers With Most Cancelled Orders',
      'no_seller_cancellation_spikes':
          'No seller cancellation spikes detected.',
      'most_reported_products': 'Most Reported Products',
      'no_product_reporting_spikes': 'No product reporting spikes detected.',
      'open_tickets': 'Open Tickets',
      'open_reports': 'Open Reports',
      'pending_refunds': 'Pending Refunds',
      'reset_password': 'Reset Password',
      'reset_password_dialog_body':
          'Enter your email address and we will send you a link to reset your password.',
      'email_address': 'Email Address',
      'enter_valid_email': 'Please enter a valid email',
      'send_reset_link': 'Send Reset Link',
      'sahla_account_access': 'Sahla account access',
      'welcome_back': 'Welcome Back!',
      'login_subtitle': 'Sign in to continue your shopping journey.',
      'enter_email': 'Please enter your email',
      'enter_valid_email_address': 'Please enter a valid email address',
      'password': 'Password',
      'enter_password': 'Please enter your password',
      'password_min_6': 'Password must be at least 6 characters',
      'forgot_password': 'Forgot Password?',
      'login': 'Login',
      'dont_have_account':
          'Don'
          't have an account?',
      'sign_up': 'Sign Up',
      'sign_in_with_google': 'Sign in with Google',
      'create_sahla_profile': 'Create your Sahla profile',
      'create_account': 'Create Account',
      'register_subtitle': 'Fill in your details to get started.',
      'join_as': 'I want to join as a:',
      'buyer': 'Buyer',
      'seller': 'Seller',
      'full_name': 'Full Name',
      'enter_full_name': 'Please enter your full name',
      'confirm_password': 'Confirm Password',
      'confirm_password_prompt': 'Please confirm your password',
      'passwords_do_not_match': 'Passwords do not match',
      'there': 'there',
      'ai_intro': 'Hi {name}, describe what you need in natural language.',
      'ai_query_hint': 'Example: budget gaming laptop under 120000 DZD',
      'ask': 'Ask',
      'ai_no_suggestions': 'No AI suggestions yet',
      'ai_no_suggestions_subtitle':
          'Ask for products by budget, quality, category, or use case.',
      'ai_products_not_loaded':
          'I could not load products yet. Try again in a moment after your feed loads.',
      'ai_no_strong_matches':
          'No strong matches found. Try adding product type, budget, or quality target.',
      'ai_found_matches':
          'I found {count} strong matches based on your intent.',
      'ai_found_matches_with_budget':
          'I found {count} strong matches based on your intent under {price} DZD.',
      'placed_on': 'Placed on',
      'view_details': 'View Details',
      'email_example_hint': 'example@mail.com',
      'enter_field': 'Enter {field}',
      'store_logo': 'Store Logo',
      'store_name_hint': 'e.g., Tech Haven',
      'enter_store_name': 'Enter store name',
      'store_description_hint': 'What do you sell?',
      'store_logo_upload_failed': 'Failed to upload store logo: {error}',
      'image_upload_failed': 'Failed to upload image: {error}',
      'personal_information': 'Personal Information',
      'name_empty': 'Name cannot be empty',
      'not_set': 'Not set',
      'email': 'Email',
      'store_information': 'Store Information',
      'no_description': 'No description',
      'ai_prompt_best_phone_camera': 'best phone camera',
      'ai_prompt_cheap_headphones': 'cheap headphones',
      'ai_prompt_laptop_students': 'laptop for students',
      'ai_prompt_fashion_women': 'fashion for women',
      'recently_viewed_empty_title': 'No recently viewed items',
      'recently_viewed_empty_subtitle': 'Items you browse will appear here.',
      'browsing_history': 'Browsing history',
      'recent_sessions_count': '{count} items from your recent sessions.',
      'how_was_experience': 'How was your experience?',
      'your_review': 'Your Review',
      'share_thoughts_hint': 'Share your thoughts about the product...',
      'submit_review': 'Submit Review',
      'login_to_review': 'Please login to submit a review',
      'review_submitted_success': 'Review submitted successfully! Thank you.',
      'checkout_prefill_failed': 'Could not load saved checkout details.',
      'saved_addresses': 'Saved Addresses',
      'choose_saved_address': 'Choose saved address',
      'saved_card_option': 'Use Saved Card',
      'saved_cards_available': 'Use one of your saved cards',
      'choose_saved_card': 'Choose saved card',
      'search_settings': 'Search settings',
      'edit_profile': 'Edit Profile',
      'terms_conditions': 'Terms and Conditions',
      'legal_effective_date': 'Effective date: April 29, 2026',
      'privacy_intro':
          'This Privacy Policy explains how Sahla collects, uses, stores, and protects your personal data.',
      'privacy_section_1_title': '1. Data We Collect',
      'privacy_section_1_body':
          'We collect profile details, order data, delivery addresses, payment metadata, app usage analytics, and support tickets.',
      'privacy_section_2_title': '2. How We Use Data',
      'privacy_section_2_body':
          'Your data is used to process orders, improve recommendations, detect fraud, provide support, and maintain app security.',
      'privacy_section_3_title': '3. Data Sharing',
      'privacy_section_3_body':
          'We share necessary information with sellers, logistics providers, and payment partners only to complete transactions and support services.',
      'privacy_section_4_title': '4. Data Retention',
      'privacy_section_4_body':
          'We retain data only as long as needed for operations, legal obligations, dispute resolution, and security purposes.',
      'privacy_section_5_title': '5. Security',
      'privacy_section_5_body':
          'We use technical and organizational safeguards to protect your data and continuously improve protections.',
      'privacy_section_6_title': '6. Your Rights',
      'privacy_section_6_body':
          'You may request access, correction, or deletion of your personal data, subject to applicable law and operational requirements.',
      'privacy_section_7_title': '7. Cookies and Device Data',
      'privacy_section_7_body':
          'We may use local storage and device identifiers to keep sessions active, remember preferences, and measure performance.',
      'privacy_section_8_title': '8. Contact',
      'privacy_section_8_body':
          'For privacy requests or concerns, contact support@sahla.app through Help Center in the app.',
      'terms_intro':
          'These Terms and Conditions govern your use of the Sahla app and related services.',
      'terms_section_1_title': '1. Account and Eligibility',
      'terms_section_1_body':
          'You must provide accurate account details and keep your credentials secure. You are responsible for activity under your account.',
      'terms_section_2_title': '2. Orders and Payments',
      'terms_section_2_body':
          'Order placement is subject to stock availability and payment confirmation. Prices and promotions may change without prior notice.',
      'terms_section_3_title': '3. Returns and Refunds',
      'terms_section_3_body':
          'Returns and refunds are handled according to seller policies and applicable consumer protection laws in your region.',
      'terms_section_4_title': '4. Prohibited Use',
      'terms_section_4_body':
          'You agree not to misuse the platform, attempt unauthorized access, upload harmful content, or interfere with service operations.',
      'terms_section_5_title': '5. Intellectual Property',
      'terms_section_5_body':
          'App branding, interfaces, and content are protected by applicable intellectual property laws. Unauthorized reuse is prohibited.',
      'terms_section_6_title': '6. Liability',
      'terms_section_6_body':
          'Sahla provides the platform as is. To the extent allowed by law, Sahla is not liable for indirect damages or losses caused by third-party sellers or services.',
      'terms_section_7_title': '7. Changes to Terms',
      'terms_section_7_body':
          'We may update these terms from time to time. Continued use of the app after updates means you accept the revised terms.',
      'terms_section_8_title': '8. Contact',
      'terms_section_8_body':
          'For legal questions, contact support@sahla.app through Help Center in the app.',
      'privacy_policy': 'Privacy Policy',
      'push_notifications': 'Push Notifications',
      'country': 'Country',
      'ai_shopping_assistant': 'AI Shopping Assistant',
      'open': 'Open',
      'ai_smart_mode': 'AI Smart Mode',
      'ai_smart_mode_subtitle':
          'Smarter suggestions and faster product discovery.',
      'app_info': 'App Info',
      'app_version': 'App Version',
      'cache_used': 'Cache Used',
      'about_app': 'About App',
      'ai_tip':
          'Tip: Use AI Assistant with natural language like "best headphones under 10000".',
      'contact_support': 'Contact Support',
      'support_help_title': 'How can we help you?',
      'support_response_time': 'Our team usually responds within 24 hours.',
      'email_us': 'Email Us',
      'call_us': 'Call Us',
      'live_chat': 'Live Chat',
      'support_live_chat_hours': 'Available 9 AM - 6 PM',
      'send_message': 'Send Message',
      'subject': 'Subject',
      'submitting': 'Submitting...',
      'support_validation_error':
          'Please enter a clear subject and a detailed message.',
      'support_ticket_submitted': 'Support ticket submitted successfully.',
      'support_ticket_failed': 'Could not submit your ticket right now.',
      'copied_to_clipboard': 'Copied to clipboard.',
      'add_new_address': 'Add New Address',
      'edit_address': 'Edit Address',
      'address_form_subtitle': 'Keep your delivery details up to date.',
      'address_title': 'Address Title (e.g. Home, Office)',
      'full_address': 'Full Address',
      'wilaya': 'Wilaya',
      'postal_code': 'Postal Code',
      'phone_number': 'Phone Number',
      'sign_in_addresses': 'Log in to manage your saved delivery addresses.',
      'address_validation_error':
          'Complete all fields with a valid 5-digit postal code.',
      'address_added': 'Address added.',
      'address_updated': 'Address updated.',
      'address_save_failed': 'Could not save the address right now.',
      'save_address': 'Save Address',
      'default_address_updated': 'Default address updated.',
      'default_address_update_failed': 'Could not update the default address.',
      'delete_address': 'Delete Address',
      'delete_address_confirm': 'Remove this address from your account?',
      'address_deleted': 'Address deleted.',
      'address_delete_failed': 'Could not delete the address.',
      'shipping_addresses': 'Shipping Addresses',
      'addresses_unavailable': 'Addresses unavailable',
      'addresses_load_error':
          'We could not load your addresses right now. Please try again later.',
      'no_addresses_saved': 'No addresses saved yet',
      'add_address_checkout': 'Add an address to speed up checkout.',
      'default_label': 'DEFAULT',
      'set_as_default': 'Set as default',
      'add_new_card': 'Add New Card',
      'save_card_checkout': 'Store a card for faster checkout.',
      'card_holder_name': 'Card Holder Name',
      'card_number': 'Card Number',
      'expiry_date': 'Expiry Date',
      'cvv': 'CVV',
      'sign_in_payment_methods': 'Log in to manage your saved payment methods.',
      'card_validation_error': 'Complete all card fields first.',
      'invalid_card_number': 'Enter a valid card number.',
      'payment_method_added': 'Payment method added.',
      'payment_method_save_failed': 'Could not save the card right now.',
      'save_card': 'Save Card',
      'primary_payment_updated': 'Primary payment method updated.',
      'primary_payment_update_failed': 'Could not update the primary card.',
      'delete_card': 'Delete Card',
      'delete_card_confirm': 'Remove this payment method from your account?',
      'payment_method_deleted': 'Payment method deleted.',
      'payment_method_delete_failed': 'Could not delete the card.',
      'payment_methods_unavailable': 'Payment methods unavailable',
      'payment_methods_load_error':
          'We could not load your payment methods right now. Please try again later.',
      'no_cards_saved': 'No cards saved yet',
      'add_card_checkout': 'Add a payment method to check out faster.',
      'primary_label': 'PRIMARY',
      'card_holder': 'CARD HOLDER',
      'expires': 'EXPIRES',
      'set_as_primary': 'Set as Primary',
      'ctr_label': 'CTR',
      'click_to_cart': 'Click to Cart',
      'cart_to_purchase': 'Cart to Purchase',
      'purchase_rate': 'Purchase Rate',
      'low_stock_alert': 'Low Stock',
    },
    'ar': {
      'app_title': 'سهلة',
      'search_hint': 'بحث عن منتجات...',
      'categories': 'الفئات',
      'featured_products': 'المنتجات المميزة',
      'add_to_cart': 'أضف إلى السلة',
      'buy_now': 'اشتري الآن',
      'profile': 'ملفي الشخصي',
      'orders': 'طلباتي',
      'wishlist': 'قائمة أمنياتي',
      'settings': 'الإعدادات',
      'language': 'اللغة',
      'dark_mode': 'الوضع الليلي',
      'logout': 'تسجيل الخروج',
      'message_store': 'مراسلة المتجر',
      'follow': 'متابعة',
      'following': 'متابع',
      'followers': 'متابعين',
      'products': 'المنتجات',
      'store_description': 'تصفح المنتجات من هذا البائع.',
      'search_in_store': 'بحث في هذا المتجر...',
      'cart': 'السلة',
      'checkout': 'الدفع',
      'total': 'المجموع',
      'recently_viewed': 'شوهد مؤخراً',
      'similar_products': 'منتجات مشابهة',
      'shopping_activity': 'نشاط التسوق',
      'account_settings': 'إعدادات الحساب',
      'support_info': 'الدعم والمعلومات',
      'shipping_address': 'عنوان الشحن',
      'payment_methods': 'طرق الدفع',
      'help_center': 'مركز المساعدة',
      'about_sahla': 'عن سهلة',
      'logout_confirm': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
      'cancel': 'إلغاء',
      'seller_dashboard': 'لوحة تحكم البائع',
      'to_pay': 'للدفع',
      'to_ship': 'للشحن',
      'to_receive': 'لاستلام',
      'to_review': 'للتقييم',
      'sahla_member': 'عضو في سهلة',
      'welcome_guest': 'أهلاً بك زائرنا',
      'sign_in_sync': 'سجل دخولك لمزامنة بياناتك',
      'explore': 'استكشف',
      'home': 'الرئيسية',
      'my_store': 'متجري',
      'help_support': 'المساعدة والدعم',
      'categories_subtitle': 'تصفح الأقسام الأكثر نشاطاً.',
      'flash_deals': 'عروض خاطفة',
      'flash_deals_subtitle': 'تخفيضات لفترة محدودة تستحق المشاهدة.',
      'featured_products_subtitle': 'منتجات مختارة بعناية من المتجر.',
      'welcome_sahla_market': 'مرحباً بك في سوق سهلة',
      'sahla_user': 'مستخدم سهلة',
      'season_sale': 'تخفيضات الموسم',
      'up_to_70_off': 'خصم يصل إلى 70%',
      'new_gadgets': 'أجهزة جديدة',
      'smart_tech_2024': 'تقنية ذكية 2024',
      'phones': 'هواتف',
      'laptops': 'لابتوبات',
      'fashion': 'أزياء',
      'home_category': 'المنزل',
      'seller_store': 'متجر البائع',
      'discover_seller_products': 'اكتشف المنتجات من هذا البائع.',
      'in_stock': 'متوفر',
      'out_of_stock': 'نفذ من المخزن',
      'reviews': 'تقييمات',
      'overview': 'نظرة عامة',
      'poster_details': 'تفاصيل الملصق',
      'poster_details_subtitle':
          'مزيد من التفاصيل المرئية التي شاركها البائع لهذا المنتج.',
      'image_load_error': 'تعذر تحميل هذه الصورة.',
      'customer_reviews': 'تقييمات العملاء',
      'no_reviews_yet': 'لا توجد تقييمات بعد.',
      'based_on': 'بناءً على',
      'customer_review_count': 'تقييم عميل',
      'customer_review_count_plural': 'تقييمات عملاء',
      'write_review': 'اكتب تقييمك',
      'first_review_prompt':
          'لا توجد تقييمات بعد. كن أول من يترك تقييماً بعد الشراء.',
      'added_to_cart': 'تمت الإضافة إلى السلة',
      'available_options': 'الخيارات المتاحة',
      'colors': 'الألوان',
      'sizes': 'المقاسات',
      'share': 'مشاركة',
      'no_written_comment': 'لا يوجد تعليق مكتوب.',
      'my_cart': 'سلتي',
      'cart_empty_title': 'سلتك فارغة',
      'cart_empty_subtitle': 'يبدو أنك لم تضف أي شيء بعد.',
      'start_shopping': 'ابدأ التسوق',
      'review_items': 'راجع منتجاتك',
      'items_ready_checkout': 'منتجات جاهزة للدفع.',
      'subtotal': 'المجموع الفرعي',
      'shipping': 'الشحن',
      'payment': 'الدفع',
      'review': 'المراجعة',
      'place_order': 'إتمام الطلب',
      'pay_now': 'ادفع الآن',
      'continue_btn': 'استمرار',
      'back': 'رجوع',
      'shipping_details': 'تفاصيل الشحن',
      'shipping_desc': 'أخبرنا أين يجب أن يذهب الطلب.',
      'wilaya_commune': 'الولاية والبلدية',
      'commune': 'البلدية',
      'commune_hint': 'أدخل بلديتك',
      'detailed_address': 'العنوان بالتفصيل',
      'address_hint': 'رقم المنزل، اسم الشارع، المبنى...',
      'delivery_type': 'نوع التوصيل',
      'select_carrier': 'اختر شركة الشحن',
      'coming_soon': 'قريباً',
      'home_delivery': 'توصيل للمنزل',
      'stop_desk': 'توصيل للمكتب (Yalidine/ZR)',
      'select_agency': 'اختر نقطة الاستلام',
      'choose_pickup_point': 'اختر مكتب الاستلام',
      'no_pickup_points_for_wilaya': 'لا توجد نقاط استلام متاحة لهذه الولاية.',
      'select_pickup_point_error':
          'اختر نقطة استلام قبل المتابعة في توصيل المكتب.',
      'stop_desk_checkout_hint':
          'في توصيل المكتب، اختر الوكالة التي سيستلم منها الزبون الطرد.',
      'delivery_status': 'حالة التوصيل',
      'sync_tracking': 'مزامنة التتبع',
      'tracking_synced': 'تمت مزامنة التتبع بنجاح.',
      'tracking_sync_failed': 'تعذر مزامنة التتبع: {error}',
      'standard_home_delivery': 'توصيل منزلي قياسي',
      'collect_from_office': 'الاستلام من المكتب',
      'est_arrival_days': 'الوصول المتوقع: 2-4 أيام',
      'available_days': 'متوفر في 1-2 أيام',
      'select_payment_method': 'اختر طريقة الدفع',
      'payment_method_desc': 'اختر الطريقة التي تريد بها إكمال الطلب.',
      'cod': 'الدفع عند الاستلام (COD)',
      'cod_desc': 'ادفع عند استلام طلبك',
      'edahabia': 'الذهبية (بريد الجزائر)',
      'edahabia_desc': 'دفع محلي سريع وآمن',
      'cib_card': 'بطاقة CIB',
      'cib_card_desc': 'دفع بالبطاقة البنكية',
      'order_summary': 'ملخص الطلب',
      'review_pricing_desc': 'راجع الأسعار قبل إتمام الطلب.',
      'shipping_fee': 'رسوم الشحن',
      'total_amount': 'المبلغ الإجمالي',
      'dzd': 'دج',
      'final_confirmation': 'التأكيد النهائي',
      'terms_privacy_agreement':
          'بالنقر على "إتمام الطلب"، فإنك توافق على شروط خدمة سهلة وسياسة الخصوصية.',
      'payment_success': 'تم الدفع بنجاح!',
      'order_placed_msg': 'تم تقديم طلبك بنجاح.\nسنخطرك عند شحنه!',
      'return_to_home': 'العودة للرئيسية',
      'cart_empty': 'سلتك فارغة',
      'notifications': 'الإشعارات',
      'sign_in_required': 'تسجيل الدخول مطلوب',
      'sign_in_notifications_msg':
          'سجل دخولك لمتابعة تحديثات الطلبات، العروض، وحالة التوصيل.',
      'notifications_unavailable': 'الإشعارات غير متوفرة',
      'notifications_load_error':
          'تعذر تحميل الإشعارات حالياً. يرجى المحاولة مرة أخرى لاحقاً.',
      'go_back': 'رجوع',
      'mark_all_read': 'تحديد الكل كمقروء',
      'no_notifications': 'لا توجد إشعارات بعد',
      'no_notifications_msg':
          'سنخطرك عند حدوث شيء مهم بخصوص طلباتك، عروضك، أو نشاط المتجر.',
      'mins_ago': 'دقائق مضت',
      'hours_ago': 'ساعات مضت',
      'days_ago': 'أيام مضت',
      'my_wishlist': 'قائمة أمنياتي',
      'wishlist_empty_title': 'قائمة أمنياتك فارغة',
      'wishlist_empty_subtitle': 'احفظ العناصر التي تعجبك لتراها هنا.',
      'search_sahla': 'ابحث في سهلة...',
      'recent_searches': 'عمليات البحث الأخيرة',
      'clear': 'مسح',
      'popular_categories': 'الفئات الشائعة',
      'popular_categories_subtitle': 'عد للأقسام التي يتصفحها الناس بكثرة.',
      'browse_category_picks': 'تصفح مختارات {category}',
      'no_products_found': 'لم يتم العثور على منتجات',
      'start_searching_msg': 'ابدأ البحث عن منتجات',
      'filter_results': 'تصفية النتائج',
      'filter_desc': 'قم بتحسين بحثك حسب السعر والتقييم.',
      'price_range': 'نطاق السعر',
      'apply_filters': 'تطبيق الفلاتر',
      'my_orders': 'طلباتي',
      'all': 'الكل',
      'orders_unavailable': 'الطلبات غير متوفرة',
      'orders_load_error': 'تعذر تحميل طلباتك حالياً. يرجى المحاولة لاحقاً.',
      'no_orders_yet': 'لا توجد طلبات بعد',
      'no_status_orders': 'لا توجد طلبات {status}',
      'order_history_desc': 'سجل مشترياتك سيظهر هنا.',
      'shop_now': 'تسوق الآن',
      'order_id': 'رقم الطلب',
      'items_count': '{count} منتجات',
      'cancel_order': 'إلغاء الطلب',
      'mark_received': 'تم الاستلام',
      'write_review_btn': 'اكتب تقييماً',
      'confirm_delivery': 'تأكيد الاستلام',
      'confirm_delivery_msg': 'هل تريد تحديد هذا الطلب كمستلم وجاهز للتقييم؟',
      'order_received_msg': 'تم تحديد الطلب كمستلم.',
      'cancel_order_title': 'إلغاء الطلب',
      'cancel_order_msg': 'هل تريد إلغاء هذا الطلب قبل شحنه؟',
      'order_cancelled_msg': 'تم إلغاء الطلب.',
      'yes': 'نعم',
      'no': 'لا',
      'awaiting_confirmation': 'بانتظار تأكيد البائع',
      'on_its_way': 'في الطريق إليك',
      'package_delivered': 'تم توصيل الطرد',
      'seller_preparing': 'البائع يجهز طلبك',
      'you_confirmed_delivery': 'لقد أكدت الاستلام',
      'order_is_cancelled': 'تم إلغاء هذا الطلب',
      'est_delivery_days': 'التوصيل المتوقع خلال 2-4 أيام',
      'messages': 'الرسائل',
      'inbox': 'البريد الوارد',
      'inbox_subtitle': 'أحدث محادثاتك مع البائعين.',
      'start_conversation': 'بدء محادثة',
      'start_conversation_subtitle':
          'ابحث عن المستخدمين بالاسم أو البريد الإلكتروني.',
      'search_users_hint': 'البحث عن مستخدمين...',
      'no_users_found': 'لم يتم العثور على مستخدمين.',
      'search_unavailable': 'البحث غير متوفر',
      'type_to_search': 'اكتب لبدء البحث',
      'messages_unavailable': 'الرسائل غير متوفرة',
      'messages_load_error':
          'تعذر تحميل محادثاتك حالياً. يرجى المحاولة لاحقاً.',
      'no_conversations_yet': 'لا توجد محادثات بعد',
      'no_conversations_msg': 'ابدأ محادثة لتظهر هنا.',
      'recipient_error': 'تعذر تحميل تفاصيل المستلم.',
      'no_messages_yet': 'لا توجد رسائل بعد',
      'image_send_error': 'تعذر إرسال الصورة.',
      'message_send_error': 'تعذر إرسال رسالتك حالياً.',
      'conversation_unavailable': 'المحادثة غير متوفرة',
      'conversation_load_error':
          'تعذر تحميل هذه المحادثة حالياً. يرجى المحاولة لاحقاً.',
      'say_hello_to': 'قل مرحباً لـ {name} لبدء المحادثة.',
      'write_message_hint': 'اكتب رسالة...',
      'edit_store_info': 'تعديل معلومات المتجر',
      'store_name': 'اسم المتجر',
      'store_description_label': 'وصف المتجر',
      'save': 'حفظ',
      'store_name_empty': 'اسم المتجر لا يمكن أن يكون فارغاً.',
      'store_not_found': 'المتجر غير موجود',
      'store_not_found_msg': 'تعذر تحديد المتجر المطلوب عرضه.',
      'add_product': 'إضافة منتج',
      'store_unavailable': 'المتجر غير متوفر',
      'store_load_error': 'تعذر تحميل المتجر حالياً.',
      'manage_storefront': 'إدارة واجهة متجرك وطلباتك.',
      'browse_seller_products': 'تصفح المنتجات من هذا البائع.',
      'message': 'رسالة',
      'pending': 'قيد الانتظار',
      'completed': 'مكتمل',
      'my_products': 'منتجاتي',
      'store_products': 'منتجات المتجر',
      'my_products_subtitle': 'كل ما هو معروض حالياً في متجرك.',
      'store_products_subtitle': 'المنتجات المتوفرة حالياً من هذا البائع.',
      'seller_approval_pending': 'موافقة البائع قيد الانتظار',
      'seller_approval_pending_msg':
          'يمكن تعديل متجرك الآن، لكن نشر المنتجات سيبقى مقفلاً حتى يوافق المشرف على حساب البائع وتضيف رقم هاتف.',
      'no_products_yet': 'لا توجد منتجات بعد',
      'no_products_yet_msg':
          'ستظهر المنتجات هنا بمجرد أن يبدأ المتجر في عرضها.',
      'no_results_found': 'لم يتم العثور على نتائج',
      'search_no_results_msg': 'حاول البحث بكلمات مفتاحية مختلفة.',
      'edit_product': 'تعديل المنتج',
      'refine_listing': 'تحسين قائمتك',
      'create_strong_listing': 'إنشاء قائمة قوية',
      'listing_subtitle': 'أضف معرض صور، صور تفصيلية، خيارات، ووصفاً واضحاً.',
      'product_gallery': 'معرض صور المنتج',
      'gallery_subtitle':
          'تظهر هذه في أعلى صفحة المنتج. الصورة الأولى تصبح الغلاف.',
      'poster_detail_images': 'صور تفصيلية للملصق',
      'poster_subtitle': 'تظهر هذه أسفل الوصف كقصة طويلة للمنتج.',
      'add_images': 'إضافة صور',
      'add_more_images': 'إضافة المزيد من الصور',
      'product_name': 'اسم المنتج',
      'product_name_hint': 'مثال: مشد رياضي احترافي',
      'price_dzd': 'السعر (دج)',
      'stock': 'المخزون',
      'main_description': 'الوصف الأساسي',
      'description_hint':
          'اكتب العرض الترويجي الأساسي للمنتج. الصور أدناه ستحول هذا إلى صفحة غنية.',
      'available_colors_label': 'الألوان المتاحة',
      'colors_subtitle': 'أضف أسماء بسيطة مثل أسود، أبيض، أزرق.',
      'add_color': 'أضف لوناً',
      'available_sizes_label': 'المقاسات المتاحة',
      'sizes_subtitle': 'أمثلة: S، M، L، XL، 42، 43.',
      'add_size': 'أضف مقاساً',
      'save_changes': 'حفظ التغييرات',
      'publish_product': 'نشر المنتج',
      'add_at_least_one_image': 'يرجى إضافة صورة واحدة على الأقل للمنتج.',
      'product_updated': 'تم تحديث المنتج بنجاح.',
      'product_published': 'تم نشر المنتج بنجاح.',
      'field_required': 'هذا الحقل مطلوب',
      'valid_non_negative_price': 'أدخل سعراً صحيحاً غير سالب',
      'valid_non_negative_stock': 'أدخل كمية مخزون صحيحة غير سالبة',
      'auth_session_expired': 'المستخدم غير مسجل الدخول أو انتهت الجلسة',
      'seller_only_publish': 'حسابات البائعين فقط يمكنها نشر المنتجات',
      'seller_publish_blocked': 'حساب البائع غير جاهز لنشر المنتجات بعد.',
      'category': 'الفئة',
      'subcategory_count': '{category} • {count} فئات فرعية',
      'selected_category': 'المحدد: {category}',
      'product_share_template':
          '{name}\n{description}\n\nالسعر: {price} {currency}\nالفئة: {category}\nتمت المشاركة من Sahla.',
      'add': 'إضافة',
      'unable_save_product': 'تعذر حفظ هذا المنتج: {error}',
      'store_orders': 'طلبات المتجر',
      'login_seller_orders_msg': 'سجل الدخول بحساب البائع لإدارة طلبات المتجر.',
      'no_orders_found': 'لم يتم العثور على طلبات',
      'no_status_orders_store': 'لا توجد طلبات {status}',
      'store_orders_empty_msg':
          'الطلبات التي تحتوي على منتجاتك ستظهر هنا بمجرد أن يطلبها العملاء.',
      'try_different_filter_msg':
          'حاول استخدام فلتر مختلف لعرض المزيد من طلبات المتجر.',
      'order_id_prefix': 'طلب رقم ',
      'qty_prefix': 'الكمية: ',
      'buyer_id_prefix': 'رقم المشتري: ',
      'buyer_name': 'المشتري',
      'buyer_phone': 'هاتف المشتري',
      'shipment_tracking': 'تتبع الشحنة',
      'tracking_number': 'رقم التتبع',
      'carrier_label': 'شركة الشحن',
      'shipment_updates_unavailable': 'تحديثات الشحنة غير متوفرة بعد.',
      'shipment_pending': 'لم يتم إنشاء الشحنة بعد.',
      'view_tracking': 'عرض التتبع',
      'retry_shipment_creation': 'إنشاء الشحنة',
      'creating_shipment': 'جارٍ إنشاء الشحنة...',
      'shipment_created': 'تم إنشاء الشحنة بنجاح.',
      'shipment_creation_failed': 'فشل إنشاء الشحنة: {error}',
      'shipment_failed': 'فشلت محاولة التوصيل',
      'elogistia_shipment_warning':
          'تم إنشاء الطلب، لكن إنشاء الشحنة في Elogistia يحتاج إلى متابعة: {error}',
      'seller_subtotal': 'المجموع الفرعي للبائع',
      'mark_as_shipped': 'تم الشحن',
      'updating_btn': 'جاري التحديث...',
      'cancel_this_order': 'إلغاء هذا الطلب؟',
      'cancel_order_notify_msg': 'سيتم إخطار المشتري بإلغاء الطلب.',
      'pending_filter': 'قيد الانتظار',
      'processing_filter': 'قيد المعالجة',
      'shipped_filter': 'تم الشحن',
      'delivered_filter': 'تم التوصيل',
      'cancelled_filter': 'ملغي',
      'total_earnings': 'إجمالي الأرباح',
      'no_orders_sign_in': 'يجب تسجيل الدخول لإدارة الطلبات.',
      'sign_in_seller_desc': 'سجل الدخول بحساب البائع لإدارة طلبات المتجر.',
      'electronics': 'إلكترونيات',
      'tablets': 'أجهزة لوحية',
      'gaming': 'ألعاب',
      'men_fashion': 'أزياء رجالية',
      'women_fashion': 'أزياء نسائية',
      'home_decor': 'ديكور المنزل',
      'sports': 'رياضة',
      'watches': 'ساعات',
      'shoes': 'أحذية',
      'accessories': 'إكسسوارات',
      'bags': 'حقائب',
      'kids': 'أطفال',
      'off': 'خصم',
      'all_products': 'كل المنتجات',
      'see_all': 'عرض الكل',
      'error': 'خطأ',
      'generic_error_retry': 'حدث خطأ ما. يرجى المحاولة مرة أخرى.',
      'authentication_failed': 'فشل تسجيل الدخول. يرجى المحاولة مرة أخرى.',
      'verify_email_before_sign_in':
          'يرجى تأكيد بريدك الإلكتروني قبل تسجيل الدخول.',
      'invalid_login_credentials':
          'البريد الإلكتروني أو كلمة المرور غير صحيحة.',
      'google_sign_in_failed': 'تسجيل الدخول عبر Google غير متاح حالياً.',
      'store_orders_load_error':
          'تعذر تحميل طلبات المتجر حالياً. يرجى المحاولة لاحقاً.',
      'update_order_failed': 'تعذر تحديث هذا الطلب حالياً.',
      'store_products_load_error': 'تعذر تحميل منتجات هذا المتجر حالياً.',
      'seller_analytics_load_error': 'تعذر تحميل تحليلات البائع حالياً.',
      'update_follow_failed': 'تعذر تحديث حالة المتابعة.',
      'update_store_details_failed': 'تعذر تحديث بيانات المتجر حالياً.',
      'upload_store_image_failed_generic': 'تعذر رفع هذه الصورة حالياً.',
      'invalid_server_response': 'أعاد الخادم استجابة غير صالحة.',
      'review_submit_failed': 'تعذر إرسال تقييمك حالياً.',
      'profile_update_failed_generic': 'تعذر تحديث ملفك الشخصي حالياً.',
      'no_items': 'لا توجد عناصر',
      'try_another_category': 'جرب فئة أخرى',
      'search_on_sahla': 'البحث في سهلة',
      'how_was_experience': 'كيف كانت تجربتك؟',
      'your_review': 'تقييمك',
      'share_thoughts_hint': 'شاركنا رأيك حول المنتج...',
      'submit_review': 'إرسال التقييم',
      'login_to_review': 'يرجى تسجيل الدخول لتقديم تقييم',
      'review_submitted_success': 'تم إرسال التقييم بنجاح! شكراً لك.',
    },
    'fr': {
      'app_title': 'Sahla',
      'search_hint': 'Rechercher des produits...',
      'categories': 'CatÃ©gories',
      'featured_products': 'Produits Vedettes',
      'add_to_cart': 'Ajouter au panier',
      'buy_now': 'Acheter maintenant',
      'profile': 'Mon Profil',
      'orders': 'Mes Commandes',
      'wishlist': 'Ma Liste de souhaits',
      'settings': 'ParamÃ¨tres',
      'language': 'Langue',
      'dark_mode': 'Mode sombre',
      'logout': 'DÃ©connexion',
      'message_store': 'Contacter la boutique',
      'follow': 'Suivre',
      'following': 'AbonnÃ©',
      'followers': 'AbonnÃ©s',
      'products': 'Produits',
      'store_description': 'Parcourir les produits de ce vendeur.',
      'search_in_store': 'Rechercher dans cette boutique...',
      'cart': 'Panier',
      'checkout': 'Paiement',
      'total': 'Total',
      'recently_viewed': 'Vus recemment',
      'similar_products': 'Produits similaires',
      'shopping_activity': 'Activite d\'achat',
      'account_settings': 'Parametres du compte',
      'support_info': 'Support et Info',
      'shipping_address': 'Adresse de livraison',
      'payment_methods': 'Modes de paiement',
      'help_center': 'Centre d\'aide',
      'about_sahla': 'A propos de Sahla',
      'profile_hub_subtitle':
          'Un espace compte plus clair avec des raccourcis et des reglages groupes.',
      'quick_access_title': 'Acces rapide',
      'quick_access_subtitle':
          'Les widgets essentiels du compte sont regroupes ici pour un acces plus rapide.',
      'order_insights_title': 'Apercu des commandes',
      'order_insights_subtitle':
          'Les statuts en direct des commandes sont separes dans des blocs plus clairs.',
      'account_tools_title': 'Outils du compte',
      'account_tools_subtitle':
          'Les informations personnelles, le paiement et les preferences sont reunis au meme endroit.',
      'support_info_title': 'Support et infos',
      'support_info_subtitle':
          'Les ressources d aide et les informations produit sont separees des reglages du compte.',
      'guest_workspace': 'Espace invite',
      'browse_mode': 'Mode navigation',
      'admin_access': 'Acces admin',
      'seller_account': 'Compte vendeur',
      'buyer_account': 'Compte acheteur',
      'email_verified_status': 'Email verifie',
      'verify_email_status': 'Verifier l email',
      'cod_blocked': 'Paiement a la livraison bloque',
      'profile_sign_in_hint':
          'Connectez-vous pour synchroniser adresses, commandes et produits enregistres.',
      'profile_store_ready':
          'La boutique est prete pour la publication et la gestion des commandes.',
      'profile_store_setup_progress':
          'La configuration vendeur est encore en cours.',
      'profile_ready_checkout':
          'Le profil est pret pour le paiement et les mises a jour de livraison.',
      'profile_add_phone':
          'Ajoutez un numero de telephone pour accelerer le paiement et le support.',
      'logout_device_hint':
          'Deconnectez-vous de cet appareil lorsque vous avez termine.',
      'awaiting_completion': 'En attente de finalisation',
      'packages_in_transit': 'Colis en transit',
      'orders_stopped': 'Commandes arretees',
      'review_ready_items': 'Articles prets a evaluer',
      'about_story_subtitle':
          'Le meme langage visuel que le profil, avec un accent sur la marque et la confiance.',
      'about_core_reasons_subtitle':
          'Les principales raisons pour lesquelles clients et vendeurs utilisent Sahla.',
      'support_shell_subtitle':
          'Acces rapide aux contacts du support et au formulaire de ticket integre.',
      'settings_shell_subtitle':
          'Langue, region, IA, cache et preferences du compte au meme endroit.',
      'password_reset_email_sent':
          'Email de reinitialisation envoye. Verifiez votre boite de reception.',
      'notifications_center_subtitle':
          'Suivez les mises a jour, promotions et changements de commande au meme endroit.',
      'discover_products': 'Decouvrir des produits',
      'search_discover_subtitle':
          'Recherchez parmi les categories, marques et tendances recentes sur Sahla.',
      'home_hub_subtitle':
          'Selections, categories et offres revisitees avec le meme style que la page profil.',
      'track_delivery_states': 'Suivre les etats de livraison',
      'saved_products': 'Produits enregistres',
      'resume_browsing': 'Reprendre la navigation',
      'moderation_tools': 'Outils de moderation',
      'store_performance': 'Performance de la boutique',
      'update_profile_details':
          'Mettez a jour vos informations et votre photo de profil.',
      'refresh_contact_info':
          'Mettez a jour vos contacts, votre avatar et vos informations vendeur.',
      'keep_delivery_locations_organized':
          'Gardez vos adresses de livraison bien organisees.',
      'manage_checkout_methods': 'Gerez vos moyens de paiement preferes.',
      'settings_summary': 'Langue, region, IA, cache et notifications.',
      'contact_support_resolve':
          'Contactez le support et resolvez les problemes du compte.',
      'read_more_marketplace':
          'En savoir plus sur la marketplace et l application.',
      'about_us_title': 'A propos',
      'about_app_name': 'Application Marketplace',
      'about_app_version': 'Version 1.0.0',
      'about_mission_title': 'Notre mission',
      'about_mission_body':
          'Nous visons une expÃ©rience e-commerce fluide et agrÃ©able en AlgÃ©rie en reliant des vendeurs fiables aux acheteurs.',
      'about_why_title': 'Pourquoi nous choisir ?',
      'about_feature_auth_title': 'Produits authentiques',
      'about_feature_auth_desc':
          'Nous veillons ÃƒÂ  lÃ¢â‚¬â„¢authenticitÃƒÂ© des produits et ÃƒÂ  la fiabilitÃƒÂ© des vendeurs.',
      'about_feature_delivery_title': 'Livraison rapide',
      'about_feature_delivery_desc':
          'Nos partenaires logistiques livrent vos commandes rapidement et de maniÃ¨re fiable.',
      'about_feature_support_title': 'Support 24/7',
      'about_feature_support_desc':
          'Notre Ã©quipe est disponible Ã  tout moment pour vous aider.',
      'logout_confirm': 'Etes-vous sur de vouloir vous deconnecter?',
      'cancel': 'Annuler',
      'seller_dashboard': 'Tableau de bord vendeur',
      'to_pay': 'A payer',
      'to_ship': 'A expedier',
      'to_receive': 'A recevoir',
      'to_review': 'A evaluer',
      'sahla_member': 'Membre Sahla',
      'welcome_guest': 'Bienvenue InvitÃ©',
      'sign_in_sync': 'Connectez-vous pour synchroniser vos donnÃ©es',
      'explore': 'Explorer',
      'home': 'Accueil',
      'my_store': 'Ma Boutique',
      'help_support': 'Aide et Support',
      'categories_subtitle': 'Parcourez les dÃ©partements les plus actifs.',
      'flash_deals': 'Ventes Flash',
      'flash_deals_subtitle': 'Baisse de prix limitÃ©e Ã  ne pas manquer.',
      'featured_products_subtitle': 'SÃ©lection de produits sur le marchÃ©.',
      'welcome_sahla_market': 'Bienvenue sur Sahla Marketplace',
      'sahla_user': 'Utilisateur Sahla',
      'season_sale': 'Soldes de saison',
      'up_to_70_off': 'Jusqu\'Ã  70% de rÃ©duction',
      'new_gadgets': 'Nouveaux Gadgets',
      'smart_tech_2024': 'Smart Tech 2024',
      'phones': 'TÃ©lÃ©phones',
      'laptops': 'Ordinateurs',
      'fashion': 'Mode',
      'home_category': 'Maison',
      'seller_store': 'Boutique du vendeur',
      'discover_seller_products': 'DÃ©couvrez les produits de ce vendeur.',
      'in_stock': 'en stock',
      'out_of_stock': 'Rupture de stock',
      'reviews': 'avis',
      'overview': 'AperÃ§u',
      'poster_details': 'DÃ©tails de l\'affiche',
      'poster_details_subtitle':
          'Plus de dÃ©tails visuels partagÃ©s par le vendeur pour ce produit.',
      'image_load_error': 'Cette image de dÃ©tail n\'a pas pu Ãªtre chargÃ©e.',
      'customer_reviews': 'Avis des clients',
      'no_reviews_yet': 'Pas encore d\'avis.',
      'based_on': 'BasÃ© sur',
      'customer_review_count': 'avis client',
      'customer_review_count_plural': 'avis clients',
      'write_review': 'ï¿½?crire un avis',
      'first_review_prompt':
          'Pas encore d\'avis. Soyez le premier client Ã  donner votre avis aprÃ¨s l\'achat.',
      'added_to_cart': 'ajoutÃ© au panier',
      'available_options': 'Options disponibles',
      'colors': 'Couleurs',
      'sizes': 'Tailles',
      'share': 'Partager',
      'no_written_comment': 'Aucun commentaire Ã©crit.',
      'my_cart': 'Mon Panier',
      'cart_empty_title': 'Votre panier est vide',
      'cart_empty_subtitle': 'On dirait que vous n\'avez encore rien ajoutÃ©.',
      'start_shopping': 'Commencer vos achats',
      'review_items': 'VÃ©rifiez vos articles',
      'items_ready_checkout': 'articles prÃªts pour le paiement.',
      'subtotal': 'Sous-total',
      'shipping': 'ExpÃ©dition',
      'payment': 'Paiement',
      'review': 'RÃ©vision',
      'place_order': 'Passer la commande',
      'pay_now': 'Payer maintenant',
      'continue_btn': 'Continuer',
      'back': 'Retour',
      'shipping_details': 'DÃ©tails d\'expÃ©dition',
      'shipping_desc': 'Dites-nous oÃ¹ la commande doit aller.',
      'wilaya_commune': 'Wilaya & Commune',
      'commune': 'Commune',
      'commune_hint': 'Entrez votre commune',
      'detailed_address': 'Adresse dÃ©taillÃ©e',
      'address_hint': 'Numï¿½ro de maison, nom de rue, bï¿½timent...',
      'delivery_type': 'Type de livraison',
      'select_carrier': 'Choisir le transporteur',
      'coming_soon': 'Bientôt disponible',
      'home_delivery': 'Livraison Ã  domicile',
      'stop_desk': 'Point relais (Yalidine/ZR)',
      'select_agency': 'Choisir un point retrait',
      'choose_pickup_point': 'Choisissez une agence stop-desk',
      'no_pickup_points_for_wilaya':
          'Aucun point stop-desk n\'est disponible pour cette wilaya.',
      'select_pickup_point_error':
          'Choisissez un point retrait avant de continuer en mode stop-desk.',
      'stop_desk_checkout_hint':
          'Pour la livraison stop-desk, choisissez l\'agence où le client récupérera le colis.',
      'delivery_status': 'Statut de livraison',
      'sync_tracking': 'Synchroniser le suivi',
      'tracking_synced': 'Le suivi a été synchronisé.',
      'tracking_sync_failed': 'Impossible de synchroniser le suivi : {error}',
      'standard_home_delivery': 'Livraison Ã  domicile standard',
      'collect_from_office': 'Retrait au bureau',
      'est_arrival_days': 'ArrivÃ©e prÃ©vue: 2-4 jours',
      'available_days': 'Disponible en 1-2 jours',
      'select_payment_method': 'SÃ©lectionnez le mode de paiement',
      'payment_method_desc':
          'Choisissez comment vous souhaitez finaliser la commande.',
      'cod': 'Paiement Ã  la livraison (COD)',
      'cod_desc': 'Payez Ã  la rÃ©ception de votre commande',
      'chargily_online': 'Chargily (CIB / Edahabia)',
      'chargily_online_desc':
          'Payez en ligne et confirmez instantanÃ©ment aprÃ¨s le paiement.',
      'edahabia': 'Edahabia (AlgÃ©rie Poste)',
      'edahabia_desc': 'Paiement local rapide et sÃ©curisÃ©',
      'cib_card': 'Carte CIB',
      'cib_card_desc': 'Paiement par carte interbancaire',
      'order_summary': 'RÃ©sumÃ© de la commande',
      'review_pricing_desc': 'VÃ©rifiez les prix avant de passer la commande.',
      'shipping_fee': 'Frais d\'expÃ©dition',
      'total_amount': 'Montant total',
      'dzd': 'DZD',
      'final_confirmation': 'Confirmation finale',
      'terms_privacy_agreement':
          'En cliquant sur "Passer la commande", vous acceptez les conditions d\'utilisation et la politique de confidentialitÃ© de Sahla.',
      'payment_success': 'Paiement rÃ©ussi !',
      'order_placed_msg':
          'Votre commande a Ã©tÃ© passÃ©e avec succÃ¨s.\nNous vous informerons de son expÃ©dition !',
      'order_placed_payment_open':
          'Commande passÃ©e. Continuez le paiement depuis la page Chargily ouverte.',
      'order_payment_open_failed':
          'Commande passÃ©e, mais la page de paiement ne s\'est pas ouverte : {error}',
      'return_to_home': 'Retour Ã  l\'accueil',
      'cart_empty': 'Votre panier est vide',
      'notifications': 'Notifications',
      'sign_in_required': 'Connexion requise',
      'sign_in_notifications_msg':
          'Connectez-vous pour voir les mises Ã  jour sur vos commandes, promotions et livraisons.',
      'notifications_unavailable': 'Notifications indisponibles',
      'notifications_load_error':
          'Impossible de charger vos notifications pour le moment. Veuillez rÃ©essayer plus tard.',
      'go_back': 'Retour',
      'mark_all_read': 'Tout marquer comme lu',
      'no_notifications': 'Aucune notification',
      'no_notifications_msg':
          'Nous vous informerons lorsqu\'un Ã©vÃ©nement important surviendra concernant vos commandes, offres ou activitÃ© en magasin.',
      'mins_ago': 'm ago',
      'hours_ago': 'h ago',
      'days_ago': 'j ago',
      'my_wishlist': 'Ma Liste de souhaits',
      'wishlist_empty_title': 'Votre liste de souhaits est vide',
      'wishlist_empty_subtitle':
          'Enregistrez les articles que vous aimez pour les voir ici.',
      'search_sahla': 'Rechercher sur Sahla...',
      'recent_searches': 'Recherches rÃ©centes',
      'clear': 'Effacer',
      'popular_categories': 'CatÃ©gories populaires',
      'popular_categories_subtitle':
          'Revenez aux sections les plus consultÃ©es.',
      'browse_category_picks': 'Parcourir les sÃ©lections {category}',
      'no_products_found': 'Aucun produit trouvÃ©',
      'start_searching_msg': 'Commencez Ã  rechercher des produits',
      'filter_results': 'Filtrer les rÃ©sultats',
      'filter_desc': 'Affinez votre recherche par prix et Ã©valuation.',
      'price_range': 'Gamme de prix',
      'apply_filters': 'Appliquer les filtres',
      'my_orders': 'Mes Commandes',
      'all': 'Tout',
      'orders_unavailable': 'Commandes indisponibles',
      'orders_load_error':
          'Impossible de charger vos commandes pour le moment. Veuillez rÃ©essayer plus tard.',
      'no_orders_yet': 'Aucune commande pour le moment',
      'no_status_orders': 'Aucune commande {status}',
      'order_history_desc': 'Votre historique d\'achat apparaÃ®tra ici.',
      'shop_now': 'Acheter maintenant',
      'order_id': 'ID',
      'items_count': '{count} articles',
      'cancel_order': 'Annuler la commande',
      'mark_received': 'Marquer comme reÃ§u',
      'write_review_btn': 'ï¿½?crire un avis',
      'confirm_delivery': 'Confirmer la livraison',
      'confirm_delivery_msg':
          'Marquer cette commande comme reÃ§ue et prÃªte pour Ã©valuation ?',
      'order_received_msg': 'Commande marquÃ©e comme reÃ§ue.',
      'cancel_order_title': 'Annuler la commande',
      'cancel_order_msg':
          'Voulez-vous annuler cette commande avant son expÃ©dition ?',
      'order_cancelled_msg': 'Commande annulÃ©e.',
      'yes': 'Oui',
      'no': 'Non',
      'awaiting_confirmation': 'En attente de confirmation du vendeur',
      'on_its_way': 'En cours de route',
      'package_delivered': 'Colis livrÃ©',
      'seller_preparing': 'Le vendeur prÃ©pare votre commande',
      'you_confirmed_delivery': 'Vous avez confirmÃ© la livraison',
      'order_is_cancelled': 'Cette commande a Ã©tÃ© annulÃ©e',
      'est_delivery_days': 'Livraison estimÃ©e sous 2-4 jours',
      'messages': 'Messages',
      'inbox': 'BoÃ®te de rÃ©ception',
      'inbox_subtitle': 'Vos derniÃ¨res conversations avec les vendeurs.',
      'start_conversation': 'DÃ©marrer une conversation',
      'start_conversation_subtitle':
          'Rechercher des utilisateurs par nom ou nom de boutique.',
      'search_users_hint': 'Rechercher des utilisateurs...',
      'no_users_found': 'Aucun utilisateur trouvÃ©.',
      'search_unavailable': 'Recherche indisponible',
      'type_to_search': 'Tapez pour commencer la recherche',
      'messages_unavailable': 'Messages indisponibles',
      'messages_load_error':
          'Impossible de charger vos conversations. Veuillez rÃ©essayer plus tard.',
      'no_conversations_yet': 'Pas encore de conversations',
      'no_conversations_msg': 'DÃ©marrez une conversation pour la voir ici.',
      'recipient_error': 'Impossible de charger les dÃ©tails du destinataire.',
      'no_messages_yet': 'Pas encore de messages',
      'image_send_error': 'Impossible d\'envoyer votre image.',
      'message_send_error':
          'Impossible d\'envoyer votre message pour le moment.',
      'conversation_unavailable': 'Conversation indisponible',
      'conversation_load_error':
          'Impossible de charger ce chat. Veuillez rÃ©essayer plus tard.',
      'say_hello_to': 'Dites bonjour Ã  {name} pour commencer la conversation.',
      'write_message_hint': 'ï¿½?crire un message...',
      'edit_store_info': 'Modifier les infos de la boutique',
      'store_name': 'Nom de la boutique',
      'store_description_label': 'Description de la boutique',
      'save': 'Enregistrer',
      'store_name_empty': 'Le nom de la boutique ne peut pas Ãªtre vide.',
      'store_not_found': 'Boutique introuvable',
      'store_not_found_msg':
          'Nous n\'avons pas pu dÃ©terminer quelle boutique afficher.',
      'add_product': 'Ajouter un produit',
      'store_unavailable': 'Boutique indisponible',
      'store_load_error':
          'Nous ne pouvons pas charger cette boutique pour le moment.',
      'manage_storefront': 'GÃ©rez votre vitrine et vos commandes.',
      'browse_seller_products': 'Parcourir les produits de ce vendeur.',
      'message': 'Message',
      'pending': 'En attente',
      'completed': 'TerminÃ©',
      'my_products': 'Mes produits',
      'store_products': 'Produits de la boutique',
      'my_products_subtitle':
          'Tout ce qui est actuellement rÃ©pertoriÃ© dans votre boutique.',
      'store_products_subtitle':
          'Produits actuellement disponibles chez ce vendeur.',
      'seller_approval_pending': 'Validation vendeur en attente',
      'seller_approval_pending_msg':
          'Votre boutique peut etre modifiee, mais la publication des produits reste bloquee jusqu a validation du compte vendeur par un administrateur et ajout d un numero de telephone.',
      'no_products_yet': 'Aucun produit pour le moment',
      'no_products_yet_msg':
          'Les produits apparaÃ®tront ici dÃ¨s que cette boutique commencera Ã  les lister.',
      'no_results_found': 'Aucun rÃ©sultat trouvÃ©',
      'search_no_results_msg':
          'Essayez de rechercher avec d\'autres mots-clÃ©s.',
      'edit_product': 'Modifier le produit',
      'refine_listing': 'Affinez votre annonce',
      'create_strong_listing': 'CrÃ©ez une annonce efficace',
      'listing_subtitle':
          'Ajoutez une galerie, des images de dÃ©tail, des options et une description claire.',
      'product_gallery': 'Galerie du produit',
      'gallery_subtitle':
          'Celles-ci apparaissent en haut de la page. La premiÃ¨re image devient la couverture.',
      'poster_detail_images': 'Images de dÃ©tail',
      'poster_subtitle':
          'Celles-ci apparaissent sous la description comme une longue histoire de produit.',
      'add_images': 'Ajouter des images',
      'add_more_images': 'Ajouter plus d\'images',
      'product_name': 'Nom du produit',
      'product_name_hint': 'ex: Support Brace Pro',
      'price_dzd': 'Prix (DZD)',
      'stock': 'Stock',
      'main_description': 'Description principale',
      'description_hint': 'RÃ©digez l\'argumentaire de base du produit.',
      'available_colors_label': 'Couleurs disponibles',
      'colors_subtitle': 'Ajoutez des noms simples comme Noir, Blanc, Bleu.',
      'add_color': 'Ajouter une couleur',
      'available_sizes_label': 'Tailles disponibles',
      'sizes_subtitle': 'Exemples : S, M, L, XL, 42, 43.',
      'add_size': 'Ajouter une taille',
      'save_changes': 'Enregistrer les modifications',
      'publish_product': 'Publier le produit',
      'add_at_least_one_image':
          'Veuillez ajouter au moins une image du produit.',
      'product_updated': 'Produit mis Ã  jour avec succÃ¨s.',
      'product_published': 'Produit publiÃ© avec succÃ¨s.',
      'field_required': 'Ce champ est obligatoire',
      'valid_non_negative_price': 'Entrez un prix valide non negatif',
      'valid_non_negative_stock':
          'Entrez une quantite de stock valide non negative',
      'auth_session_expired': 'Utilisateur non connecte ou session expiree',
      'seller_only_publish':
          'Seuls les comptes vendeurs peuvent publier des produits',
      'seller_publish_blocked':
          'Votre compte vendeur n est pas encore pret a publier des produits.',
      'category': 'CatÃ©gorie',
      'subcategory_count': '{category} • {count} sous-categories',
      'selected_category': 'Selectionne : {category}',
      'product_share_template':
          '{name}\n{description}\n\nPrix : {price} {currency}\nCategorie : {category}\nPartage depuis Sahla.',
      'add': 'Ajouter',
      'unable_save_product': 'Impossible d\'enregistrer ce produit : {error}',
      'store_orders': 'Commandes de la boutique',
      'login_seller_orders_msg':
          'Connectez-vous avec votre compte vendeur pour gÃ©rer les commandes.',
      'no_orders_found': 'Aucune commande trouvÃ©e',
      'no_status_orders_store': 'Aucune commande {status}',
      'store_orders_empty_msg':
          'Les commandes contenant vos produits apparaÃ®tront ici.',
      'try_different_filter_msg':
          'Essayez un autre filtre pour voir plus de commandes.',
      'order_id_prefix': 'Commande #',
      'qty_prefix': 'QtÃ© : ',
      'buyer_id_prefix': 'ID Acheteur : ',
      'buyer_name': 'Acheteur',
      'buyer_phone': 'TÃ©lÃ©phone acheteur',
      'shipment_tracking': 'Suivi d\'expédition',
      'tracking_number': 'Numéro de suivi',
      'carrier_label': 'Transporteur',
      'shipment_updates_unavailable':
          'Les mises à jour d\'expédition ne sont pas encore disponibles.',
      'shipment_pending': "L'expédition n'a pas encore été créée.",
      'view_tracking': 'Voir le suivi',
      'retry_shipment_creation': "Créer l'expédition",
      'creating_shipment': "Création de l'expédition...",
      'shipment_created': "L'expédition a été créée avec succès.",
      'shipment_creation_failed':
          "La création de l'expédition a échoué : {error}",
      'shipment_failed': 'La tentative de livraison a échoué',
      'elogistia_shipment_warning':
          'La commande est créée, mais la création de l\'expédition Elogistia nécessite une vérification : {error}',
      'seller_subtotal': 'Sous-total vendeur',
      'mark_as_shipped': 'Marquer comme expÃ©diÃ©',
      'mark_as_delivered': 'Marquer comme livrÃ©',
      'mark_order_delivered_title': 'Marquer cette commande comme livrÃ©e ?',
      'mark_order_delivered_msg':
          'Cela notifiera l\'acheteur que la commande a Ã©tÃ© livrÃ©e.',
      'status_pending_approval': 'EN ATTENTE D\'APPROBATION',
      'status_approved': 'APPROUVÃƒâ€°',
      'status_verified': 'VÃƒâ€°RIFIÃƒâ€°',
      'status_cod_blocked': 'COD BLOQUÃƒâ€°',
      'status_suspended': 'SUSPENDU',
      'status_open': 'Ouvert',
      'status_in_progress': 'En cours',
      'status_reviewing': 'En rÃ©vision',
      'status_resolved': 'RÃ©solu',
      'status_closed': 'FermÃ©',
      'status_dismissed': 'ClassÃ©',
      'status_rejected': 'RejetÃ©',
      'status_refunded': 'RemboursÃ©',
      'reporter_label': 'Signaleur',
      'seller_label': 'Vendeur',
      'updating_btn': 'Mise Ã  jour...',
      'cancel_this_order': 'Annuler cette commande ?',
      'cancel_order_notify_msg':
          'Cela informera l\'acheteur que la commande a Ã©tÃ© annulÃ©e.',
      'pending_filter': 'En attente',
      'processing_filter': 'En traitement',
      'shipped_filter': 'ExpÃ©diÃ©',
      'delivered_filter': 'LivrÃ©',
      'cancelled_filter': 'AnnulÃ©',
      'total_earnings': 'Total des gains',
      'no_orders_sign_in': 'Connexion requise pour gÃ©rer les commandes.',
      'sign_in_seller_desc':
          'Connectez-vous avec votre compte vendeur pour gÃ©rer les commandes.',
      'electronics': 'ï¿½?lectronique',
      'tablets': 'Tablettes',
      'gaming': 'Jeux vidÃ©o',
      'men_fashion': 'Mode homme',
      'women_fashion': 'Mode femme',
      'home_decor': 'DÃ©coration',
      'sports': 'Sports',
      'watches': 'Montres',
      'shoes': 'Chaussures',
      'accessories': 'Accessoires',
      'bags': 'Sacs',
      'kids': 'Enfants',
      'off': 'DE Rï¿½?DUCTION',
      'all_products': 'Tous les produits',
      'see_all': 'Voir tout',
      'error': 'Erreur',
      'generic_error_retry': 'Une erreur est survenue. Veuillez réessayer.',
      'authentication_failed':
          "L'authentification a échoué. Veuillez réessayer.",
      'verify_email_before_sign_in':
          'Veuillez confirmer votre e-mail avant de vous connecter.',
      'invalid_login_credentials': 'Adresse e-mail ou mot de passe incorrect.',
      'google_sign_in_failed':
          'La connexion Google est indisponible pour le moment.',
      'store_orders_load_error':
          'Impossible de charger les commandes de la boutique pour le moment.',
      'update_order_failed':
          'Impossible de mettre à jour cette commande pour le moment.',
      'store_products_load_error':
          'Impossible de charger les produits de cette boutique pour le moment.',
      'seller_analytics_load_error':
          'Impossible de charger vos statistiques vendeur pour le moment.',
      'update_follow_failed':
          'Impossible de mettre à jour le suivi pour le moment.',
      'update_store_details_failed':
          'Impossible de mettre à jour les détails de la boutique pour le moment.',
      'upload_store_image_failed_generic':
          "Impossible d'envoyer cette image pour le moment.",
      'invalid_server_response': 'Le serveur a renvoyé une réponse invalide.',
      'review_submit_failed': "Impossible d'envoyer votre avis pour le moment.",
      'profile_update_failed_generic':
          'Impossible de mettre à jour votre profil pour le moment.',
      'no_items': 'Aucun article',
      'try_another_category': 'Essayez une autre catÃ©gorie',
      'search_on_sahla': 'Rechercher sur Sahla',
      'how_was_experience': 'Comment s\'est passÃ©e votre expÃ©rience ?',
      'your_review': 'Votre avis',
      'share_thoughts_hint': 'Partagez votre avis sur le produit...',
      'submit_review': 'Envoyer l\'avis',
      'login_to_review': 'Veuillez vous connecter pour laisser un avis',
      'review_submitted_success': 'Avis envoyÃ© avec succÃ¨s ! Merci.',
    },
  };
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'ar', 'fr'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    AppLocalizations localizations = AppLocalizations(locale);
    await localizations.load();
    return localizations;
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => true;
}

extension LocalizationExtension on BuildContext {
  String translate(String key) =>
      AppLocalizations.of(this)?.translate(key) ?? key;
}
